name: ci-frontend

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: titanium/babylon-frontend

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
        working-directory: ./frontend


  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./frontend
    - run: npm run lint
      working-directory: ./frontend
    - run: npm run build
      working-directory: ./frontend

  
  build-docker:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        working-directory: ./frontend
